name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ec2-16-171-239-29.eu-north-1.compute.amazonaws.com
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu/docker-github-actions"

      - name: Run Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-16-171-239-29.eu-north-1.compute.amazonaws.com
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/docker-github-actions
            sudo docker-compose down
            sudo docker-compose up --build -d
